const fs = require('fs');
const acorn = require('acorn');
const html = fs.readFileSync('index.html', 'utf8');

const regex = /on[a-z]+="([^"]*)"/g;
let match;
while ((match = regex.exec(html)) !== null) {
    let attr = match[0];
    if (!attr.startsWith('onclick') && !attr.startsWith('onchange') && !attr.startsWith('oninput') && !attr.startsWith('onmouseover') && !attr.startsWith('onmouseout')) continue;
    let code = match[1];
    
    // If it contains template literal syntax, it's likely generated by JS, so we can't easily statically analyze it without context, but let's try to mock it.
    let testCode = code.replace(/\$\{[^}]+\}/g, '1');
    
    try {
        acorn.parse(testCode, { ecmaVersion: 2020 });
    } catch (e) {
        console.error('Syntax Error in inline handler:', attr);
        console.error(e);
    }
}
console.log('Done checking inline handlers');
